### ISSUE TITLE
11/22 Meeting - Milestone 2 Tasks

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#20]
### Reflections of last week (10 mins)
- Re-group (Briefly understand our backgrounds again)
- What we did well
- What we can improve (Process, Git, Communications... etc)

### Milestone 2 checklist (15 mins)
- [x] Write a script that reads the downloaded data and performs and data cleaning/pre-processing, transforming, and/or splitting
   - [x] `download script`: improve the script based on feedbacks from TA - **Carry forward to M3**
   - [x] `download script`: choose a more descriptive filename than the one used for illustrative purpose
   - [x] `Data cleaning/pre-processing script`: Create the script that takes data from `download script`
- [x] Write a script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that data set
    - [x] `EDA script`: A script which creates exploratory data visualisations and tables
    - [x] Improve the EDA analysis
- [x] Write a script that performs some statistical or machine learning analysis and summarizes the results as a figure(s) and a table(s)
    - [x] `Analysis script`: A script that performs statistical or ML analysis and summarizes the results as figures and tables.
- [ ] Write a literate code document which presents your analysis and findings
    - [ ] Written narrative in `.Rmd` or `.ipynb` that introduces and justifies our questions etc
- [ ] Iterate on work done for milestone 1 as required per TA feedback

### Division of work and timeline (10 mins)
TBD

### AOB (5 mins)
TBD

**Comment by thomassiu** [comment]
Here are the meeting re-cap:

- For simplicity, we will use `Python` as the programming language. That is also easier to manage for ML.
- Branching on the forked repo is not a must. As long as we can manage the PR that will be OK. 
- Thomas did a trial on:

1. git pull from upstream to local
2. Create a feature branch in forked repo
3. Make a PR directly to the upstream main branch
4. Once it is merged, delete the forked feature branch
5. git pull again from upstream to update the main branch

We should all work together but the following are the person to take charge.
Download script + data pre-processing: Thomas
EDA script + EDA enhancement: Shi Yan
Analysis and model training: Ramiro
Literate code document: Jasmine

**Comment by thomassiu** [comment]
Pull request made for pre-processing script. At the same time models are trained for discussions.

**Comment by thomassiu** [comment]
Have also explored using jupyter book - need to download to view

https://github.com/thomassiu/DSCI_522_Crime_Prediction_Vancouver/tree/jupyter_book_demo/reports

**Comment by sy25wang** [comment]
Pull request made for eda analysis.

**Comment by thomassiu** [comment]
All tasks completed.
