### ISSUE TITLE
11/27 Meeting - Milestone 2 final checkpoint

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#43]
### Milestone 2 tasks revisited
- [x] Write a script that reads the downloaded data and performs and data cleaning/pre-processing, transforming, and/or splitting
   - [x] `download script`: improve the script based on feedbacks from TA - **Carry forward to M3**
   - [x] `download script`: choose a more descriptive filename than the one used for illustrative purpose
   - [x] `Data cleaning/pre-processing script`: Create the script that takes data from `download script`
- [x] Write a script which creates exploratory data visualization(s) and table(s) that are useful to help the reader/consumer understand that data set
    - [x] `EDA script`: A script which creates exploratory data visualisations and tables
    - [x] Improve the EDA analysis
- [x] Write a script that performs some statistical or machine learning analysis and summarizes the results as a figure(s) and a table(s)
    - [x] `Analysis script`: A script that performs statistical or ML analysis and summarizes the results as figures and tables.
- [x] Write a literate code document which presents your analysis and findings
    - [x] Written narrative in `.Rmd` or `.ipynb` that introduces and justifies our questions etc
- [x] Iterate on work done for milestone 1 as required per TA feedback - **Carry forward to M3**

### Outstanding issues
TBD

### AOB
TBD

**Comment by thomassiu** [comment]
milestone 2 done and completed
