### ISSUE TITLE
11/29 Meeting - Milestone 3 Tasks

### ISSUE THREAD

**Issue by sy25wang** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#51]
### Milestone 3 checklist
- [x] Write a Makefile to run the others in sequence, hard coding in the appropriate arguments
   - [x] live in the project’s root directory and be named `Makefile`
   - [x] be well documented (using the project README and comments inside the Makefile to explain what it does and how to use it)
   - [x] have a `all:` target so that you can easily run the entire analysis from top to bottom by running `make all` at the command line
   - [x] have a `clean:` target so that you can easily “undo” your analysis by running `make clean` at the command line
- [x] Use proper grammar and full sentences in your README and report. Point form may occur, but should be less than 10% of your written documents.
- [x] Have a well organized lab repo/directory structure
- [x] All members have over 20+ commit in your git log starting Milestone. Makes sure your commit messages meaningful
- [x] Create another release for your project repo (with an appropriate name)
- [x] Submit the URL to your project in your milestone3 repo’s `README.md` and URL for release
