### ISSUE TITLE
Milestone 4 Final Checks

### ISSUE THREAD

**Issue by sy25wang** [UBC-MDS/DSCI_522_Crime_Prediction_Vancouver#72]
- [x] Comments on peer reviews (at least 4 points and fix them)
- [x] Resize Makefile.png and include it in the README.md
- [x] Finalize project structure (clean the content)
- [x] Create another release for your project repo (1.0.0)
- [x] Submit 3 links to Canvas (release, repo, peer review issue page)

**Comment by sy25wang** [comment]
Issue page
https://github.com/UBC-MDS/data-analysis-review-2021/issues/8

**Comment by thomassiu** [comment]
I've completed 2 and 3 and will push it later.

**Comment by RamiroMejia** [comment]
Check 1. :

I added 5 comments on peer reviews, please check them and feel free to add more points : 

https://github.com/UBC-MDS/data-analysis-review-2021/issues/8#issuecomment-990616454

**Comment by sy25wang** [comment]
> Check 1. :
> 
> I added 5 comments on peer reviews, please check them and feel free to add more points :
> 
> [UBC-MDS/data-analysis-review-2021#8 (comment)](https://github.com/UBC-MDS/data-analysis-review-2021/issues/8#issuecomment-990616454)

I replied two feedbacks specifically. Let me know if anyone else want to take the rest.

**Comment by thomassiu** [comment]
> > Check 1. :
> > I added 5 comments on peer reviews, please check them and feel free to add more points :
> > [UBC-MDS/data-analysis-review-2021#8 (comment)](https://github.com/UBC-MDS/data-analysis-review-2021/issues/8#issuecomment-990616454)
> 
> I replied two feedbacks specifically. Let me know if anyone else want to take the rest.

Believe we just need to pick a total of 4 points among 3 peer reviews? So we should have fulfilled the need.

**Comment by thomassiu** [comment]
All done!
